backend:
  name: github
  repo: AhmadShamsi376/umeed-e-sahar
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

site_url: "https://gleaming-semifreddo-903afc.netlify.app"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: [Society, Economics, History, Editorial, Literature]}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Cover image", name: "cover", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "poetry"
    label: "Poetry & Literature"
    folder: "content/poetry"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
